@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json
  
###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiI4ZDhiODRkZCIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImFnZSI6IjI1IiwiYXVkIjoid2VhdGhlcmZvcmVjYXN0YXBpIiwibmJmIjoxNzM0MzYyODE1LCJleHAiOjE3NDIxMzg4MTUsImlhdCI6MTczNDM2MjgxNiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.hNUW98jorwGAx9ZnPKLw4TVwYQfHuAxmknyw8IFauJI
Accept: application/json 