@WebApiAuthentication.Api_HostAddress = https://localhost:7277

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Accept: application/json
  
###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiJmODg3ZDRlMCIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImFnZSI6IjI1IiwiYXVkIjoid2VhdGhlcmZvcmVjYXN0YXBpIiwibmJmIjoxNzM0NTE3NDc2LCJleHAiOjE3NDIyOTM0NzYsImlhdCI6MTczNDUxNzQ3NywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.yQ8beFsznBc0TBkVlq_h8jEw4JxcHi1W1XqtAWjCtZ8
Accept: application/json 

###

GET {{WebApiAuthentication.Api_HostAddress}}/weatherforecast/abc123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImtldmluIiwic3ViIjoia2V2aW4iLCJqdGkiOiJmODg3ZDRlMCIsInN1YnNjcmlwdGlvbmxldmVsIjoiZ29sZCIsImFnZSI6IjI1IiwiYXVkIjoid2VhdGhlcmZvcmVjYXN0YXBpIiwibmJmIjoxNzM0NTE3NDc2LCJleHAiOjE3NDIyOTM0NzYsImlhdCI6MTczNDUxNzQ3NywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.yQ8beFsznBc0TBkVlq_h8jEw4JxcHi1W1XqtAWjCtZ8
Accept: application/json 